name: Docker Image CI 64 bits

on:
  push:
    branches: [ "arm64" ]
  pull_request:
    branches: [ "arm64" ]

jobs:

  build:
    runs-on: self-hosted
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      # - run: echo $SHA
      #   env:
      #     SHA: ${{ env.SHA }}
      - name: Build the Docker image 64bits
        run: docker build . --file Dockerfile --tag my-image-name:${{ steps.short-sha.outputs.sha }} --build-context 64bits
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push with commit number
        uses: docker/build-push-action@v4
        with:
            push: true
            tags: leto1210/duplicacy-web-arm:${{ steps.short-sha.outputs.sha }}
            context: .
            platforms: linux/arm64
      - name: Build and push with latest tag
        uses: docker/build-push-action@v4
        with:
            push: false
            tags: leto1210/duplicacy-web-arm:latest
