name: Do things every 5 days

on:
  schedule:
    - cron: "0 0 */5 * *" # Exécution tous les 5 jours à minuit

jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - name: Print short SHA
        run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push with commit number
        uses: docker/build-push-action@v5
        with:
            push: true
            tags: |
              leto1210/duplicacy-web-arm:${{ steps.short-sha.outputs.sha }}
              leto1210/duplicacy-web-arm:arm64
            file: ./64bits/Dockerfile
            platforms: linux/arm64ile
            platforms: linux/arm64