name: Trivy Scan

on:
  workflow_dispatch: # Permet de déclencher manuellement le workflow
  workflow_run:
    workflows:
      - Docker Image CI 32 bits and 64 bits
    types:
      - completed

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  scan:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: armv7
            image_tag: latest-armv7
          - arch: arm64
            image_tag: latest-arm64

    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Scan Container Image (${{ matrix.arch }})
        id: scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # 0.36.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/leto1210/duplicacy-web-arm/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/leto1210/duplicacy-web-arm/trivy-java-db
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ github.token }}
        with:
          cache: true
          exit-code: 1
          ignore-unfixed: true
          image-ref: docker.io/leto1210/duplicacy-web-arm:${{ matrix.image_tag }}
          format: 'sarif'
          output: 'duplicacy-web-arm_trivy-results-${{ matrix.arch }}.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab (${{ matrix.arch }})
        uses: github/codeql-action/upload-sarif@f52b05f4acaaa234e44466e66d29050e135ea9ef # v4.36.0
        if: always()
        with:
          sarif_file: 'duplicacy-web-arm_trivy-results-${{ matrix.arch }}.sarif'
