name: Trivy Scan

on:
  workflow_dispatch: # Permet de déclencher manuellement le workflow
  workflow_run:
    workflows:
      - Docker Image CI 32 bits and 64 bits
    types:
      - completed

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set short SHA
      #   id: short-sha
      #   run: echo "sha=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_ENV

      #- name: Install ORAS
      #  id: oras
      #  uses: oras-project/setup-oras@v1.2.1

      - name: Authenticate to GHCR
        id: ghcr
        shell: bash
        run: |
          oras login ghcr.io \
            -u ${{ github.actor }} \
            -p ${{ github.token }}

      # - name: Pull Trivy DBs from GHCR
      #   id: pull
      #   shell: bash
      #   run: |
      #     oras pull ghcr.io/leto1210/duplicacy-web-arm/trivy-db:2
      #     oras pull ghcr.io/leto1210/duplicacy-web-arm/trivy-java-db:1
      # - name: Debug Docker Image
      #   run: |
      #     docker pull docker.io/leto1210/duplicacy-web-arm:latest-arm64
      #     docker inspect docker.io/leto1210/duplicacy-web-arm:latest-arm64

      - name: Scan Container Image
        id: scan
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/leto1210/duplicacy-web-arm/trivy-db,public.ecr.aws/aquasecurity/trivy-db,ghcr.io/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/leto1210/duplicacy-web-arm/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ github.token }}
        with:
          cache: true
          exit-code: 0
          ignore-unfixed: true
          #image-ref: docker.io/leto1210/duplicacy-web-arm:${{ env.sha }}-arm64
          image-ref: docker.io/leto1210/duplicacy-web-arm:latest-arm64
          format: 'sarif'
          output: 'duplicacy-web-arm_trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'duplicacy-web-arm_trivy-results.sarif'
