name: Trivy Scan

on:
  workflow_dispatch: # Permet de déclencher manuellement le workflow
  workflow_run:
    workflows:
      - Docker Image CI 32 bits and 64 bits
    types:
      - completed

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: self-hosted

    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Scan Container Image
        id: scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/leto1210/duplicacy-web-arm/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/leto1210/duplicacy-web-arm/trivy-java-db
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ github.token }}
        with:
          cache: true
          exit-code: 0
          ignore-unfixed: true
          image-ref: docker.io/leto1210/duplicacy-web-arm:latest-arm64
          format: 'sarif'
          output: 'duplicacy-web-arm_trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@c03c7286b23a2c4c2a10abb7eed1512b7580b4c5 # v3.34.1
        if: always()
        with:
          sarif_file: 'duplicacy-web-arm_trivy-results.sarif'
